export enum PhysicalActivity {
    INACTIVE = 'INCTIVE',
    SLIGHTLY_ACTIVE = 'SLIGHTLY_ACTIVE',
    MODERATELY_ACTIVE = 'MODERATELY_ACTIVE',
    ACTIVE = 'ACTIVE',
    HIGHLY_ACTIVE = 'HIGHLY_ACTIVE',
}
