name: Nx

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: cache-node-modules-${{ hashFiles('yarn.lock') }}
            - run: yarn nx affected --parallel --target=test

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: cache-node-modules-${{ hashFiles('yarn.lock') }}
            - run: yarn nx affected --parallel --target=lint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: cache-node-modules-${{ hashFiles('yarn.lock') }}
            - run: yarn nx affected --parallel --target=build --prod
