name: Nx

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    install-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: cache-node-modules-${{ hashFiles('yarn.lock') }}
            - name: Cache Nx
              uses: actions/cache@v2
              with:
                  path: node_modules/.cache/nx
                  key: cache-nx-${{ hashFiles('yarn.lock') }}
                  restore-keys: cache-nx-${{ hashFiles('yarn.lock') }}-
            - name: yarn install
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install --pure-lockfile

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn nx affected --parallel --target=test

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn nx affected --parallel --target=lint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn nx affected --parallel --target=build --prod
